# Use Dockerized infrastructure
sudo: enabled

# Use node_js environnement
language: python
python: 
  - "3.6"

# Cache Gcloud SDK between commands
cache:
  directories:
    - "$HOME/google-cloud-sdk/"

# Install services
services:
  - docker

before_install:
  - chmod +x ci/setup-gcp.sh
  - sudo curl -fsSL "https://github.com/GoogleCloudPlatform/docker-credential-gcr/releases/download/v${VERSION}/docker-credential-gcr_${OS}_${ARCH}-${VERSION}.tar.gz" \ | tar xz --to-stdout ./docker-credential-gcr \ > /usr/bin/docker-credential-gcr && chmod +x /usr/bin/docker-credential-gcr
  - /usr/bin/docker-credential-gcr configure-docker
  - ci/setup-gcp.sh
  - docker build -t gcr.io/${PROJECT_NAME}/${LABEL_NAME}:$TRAVIS_COMMIT -f ./Dockerfile .

before_deploy:
  - chmod +x ./ci/prod-deploy.sh

deploy:
  - provider: script
    script: ./ci/prod-deploy.sh
    skip_cleanup: true
    on:
      branch: master