# Use Dockerized infrastructure
sudo: enabled

# Use node_js environnement
language: python
python: 
  - "3.6"

# Cache Gcloud SDK between commands
cache:
  directories:
    - "$HOME/google-cloud-sdk/"

# Install services
services:
  - docker

before_install:
  - chmod +x ci/setup-gcp.sh
  - ci/setup-gcp.sh

before_deploy:
  - chmod +x ./ci/prod-deploy.sh

deploy:
  - provider: script
    script: ./ci/prod-deploy.sh
    skip_cleanup: true
    on:
      branch: master