version: '3.7'

services: 
  # api
  api: 
    container_name: email-scheduler
    build: ./
    # command: flask run
    working_dir: /usr/src/email-scheduler
    env_file: .env
    environment: 
      FLASK_APP: server.py
      FLASK_DEBUG: 'true'
      FLASK_ENV: development
    links: 
      - postgres
    ports: 
      - "5555:5000"
    volumes: 
      - .:/usr/src/email-scheduler

  # redis db
  postgres:
    image: postgresql
    ports: 
      - "5432:5432"