version: '3.7'

services: 
  # api
  api: 
    container_name: email-scheduler
    build: ./
    # command: flask run
    working_dir: /usr/src/email-scheduler
    env_file: .env
    environment: 
      FLASK_APP: server.py
      FLASK_DEBUG: 'true'
      FLASK_ENV: development
      POSTGRES_URI: 'postgresql://postgres:password@postgres'
    links: 
      - postgres
    ports: 
      - "5555:5000"
    volumes: 
      - .:/usr/src/email-scheduler

  # postgres db
  postgres:
    image: postgres
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password