apiVersion: skaffold/v1beta11
kind: Config
build: 
  artifacts: 
  - image: mikkelwestermann/email-automation
  local: 
    push: false
deploy: 
  kubectl:
    manifests:
      - k8s/k8s-*
profiles: 
  - name: local
    build: 
      artifacts: 
      - image: mikkelwestermann/email-automation
      local: 
        push: false
    deploy: 
      kubectl: 
        manifests: 
          - k8s/k8s-*