apiVersion: skaffold/v1beta11
kind: Config
build: 
  artifacts: 
  - image: gcr.io/influencio-274918/email-automation
  local: 
    push: false
deploy: 
  kubectl:
    manifests:
      - k8s/local/k8s-*
profiles: 
  - name: production
    build: 
      googleCloudBuild: 
        projectId: email-automation
    deploy: 
      kubectl: 
        manifests: 
          - k8s/production/k8s-*