# service 
apiVersion: v1
kind: Service
metadata:
  name: email-automation
spec: 
  selector:
    name: email-automation
  ports:
    - port: 5555
      protocol: TCP
      targetport: email-automation
    type: LoadBalancer

---
# deployment
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: email-automation
  labels: 
    name: email-automation
  spec: 
    replicas: 1
    strategy: 
      type: RollingUpdate
    selector:
      matchLabels: 
        name: email-automation
    template: 
      metadata: 
        name: email-automation
        labels: 
          name: email-automation
      spec: 
        containers: 
          - name: email-automation
            image: mikkelwestermann/email-automation
            ports: 
              - containerPort: 5000
                name: email-automation
            env: 
              - name: FLASK_APP
                value: server.py
              - name: FLASK_DEBUG
                value: 'true'
              - name: FLASK_ENV
                value: development
              - name: POSTGRES_URI
                value: postgresql://postgres:password@postgres