# service 
apiVersion: v1
kind: Service
metadata:
  name: email-automation
spec: 
  selector:
    name: email-automation
  ports:
    - port: 5000
      protocol: TCP
      targetPort:  5000

---
# deployment
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: email-automation
  labels: 
    name: email-automation
spec: 
  replicas: 1
  strategy: 
    type: RollingUpdate
  selector:
    matchLabels: 
      name: email-automation
  template: 
    metadata: 
      name: email-automation
      labels: 
        name: email-automation
    spec: 
      containers: 
        - name: email-automation
          image: gcr.io/influencio-274918/email-automation:latest
          ports: 
            - containerPort: 5000
              name: email-auto
          env: 
            - name: FLASK_APP
              value: server.py
            - name: FLASK_DEBUG
              value: 'true'
            - name: FLASK_ENV
              value: staging
            - name: POSTGRES_URI
              valueFrom: 
                secretKeyRef: 
                  name: email-automation-secrets
                  key: POSTGRES_URI
            - name: FRONTEND_BASE_URL
              value: https://staging.influencio.dk
            - name: SENDGRID_API_KEY
              valueFrom: 
                secretKeyRef: 
                  name: email-automation-secrets
                  key: SENDGRID_API_KEY
            - name: SENDGRID_SENDER
              value: hi@influencio.dk
            - name: DEFAULT_TEMPLATE_ID
              valueFrom: 
                secretKeyRef: 
                  name: email-automation-secrets
                  key: DEFAULT_TEMPLATE_ID
            - name: ERROR_EMAIL_TEMPLATE
              valueFrom: 
                secretKeyRef: 
                  name: email-automation-secrets
                  key: ERROR_EMAIL_TEMPLATE
            - name: DEFAULT_EMAIL_RECIPIENT
              value: mikkel@influencio.dk